version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-angular
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/usr/share/nginx/html:ro
    ports:
      - 8880:80
